# Generated by Django 4.2.6 on 2023-12-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('en_alquiler', 'En alquiler'), ('en_venta', 'En venta'), ('vendido', 'Vendido'), ('alquilado', 'Alquilado'), ('no_disponible', 'No disponible')], default='no_disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón'), ('cochera', 'Cochera'), ('terreno', 'Terreno')], max_length=20)),
                ('habitaciones', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('baños', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('balcon', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('pileta', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('garage', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('valor_alquiler', models.CharField(max_length=20)),
                ('valor_venta', models.CharField(max_length=20)),
                ('expensas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('resuelto', 'Resuelto'), ('no_resuelto', 'No resuelto'), ('en_proceso', 'En proceso')], max_length=20)),
                ('reclamante', models.CharField(choices=[('inquilino', 'Inquilino'), ('propietario', 'Propietario'), ('comprador', 'Comprador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reparymant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('gas', 'Gas'), ('estructura', 'Estructura'), ('varios', 'Varios')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('resuelto', 'Resuelto'), ('no_resuelto', 'No resuelto'), ('en_proceso', 'En proceso')], max_length=20)),
                ('costo', models.CharField(max_length=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
            ],
        ),
        migrations.CreateModel(
            name='propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('propiedades', models.ManyToManyField(to='appbroker.propiedades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('valor_alquiler', models.CharField(max_length=20)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.inquilinos')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propietarios')),
            ],
        ),
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venta', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.compradores')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
            ],
        ),
        migrations.AddField(
            model_name='compradores',
            name='propiedades',
            field=models.ManyToManyField(to='appbroker.propiedades'),
        ),
    ]
