# Generated by Django 5.0.1 on 2024-01-26 02:05

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('en_alquiler', 'En alquiler'), ('en_venta', 'En venta'), ('vendido', 'Vendido'), ('alquilado', 'Alquilado'), ('no_disponible', 'No disponible')], default='no_disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón'), ('cochera', 'Cochera'), ('terreno', 'Terreno')], max_length=20)),
                ('habitaciones', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('baños', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('balcon', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('pileta', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('garage', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('valor_alquiler', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_venta', models.CharField(blank=True, max_length=20, null=True)),
                ('expensas', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('resuelto', 'Resuelto'), ('no_resuelto', 'No resuelto'), ('en_proceso', 'En proceso')], max_length=20)),
                ('reclamante', models.CharField(blank=True, choices=[('inquilino', 'Inquilino'), ('propietario', 'Propietario'), ('comprador', 'Comprador')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reclamos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Nombre de usuario ya existente'}, max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario solo puede contener letras, números y @/./+/-/_.', regex='^[\\w.@+-]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('invitado', 'Invitado'), ('inquilino', 'Inquilino'), ('inmobiliaria', 'Inmobiliaria'), ('propietario', 'Propietario'), ('comprador', 'Comprador')], max_length=15)),
                ('telefono', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_inmobiliaria', related_query_name='usuario', to='auth.group', verbose_name='Grupo al que pertenece')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='permisos_usuario_inmobiliaria', related_query_name='usuario', to='auth.permission', verbose_name='Permisos del usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('valor_alquiler', models.CharField(max_length=20)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.inquilinos')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.contratos')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='inquilinos',
            name='propiedades',
            field=models.ManyToManyField(to='appbroker.propiedades'),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venta', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.compradores')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.AddField(
            model_name='compradores',
            name='propiedades',
            field=models.ManyToManyField(to='appbroker.propiedades'),
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('documento', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('propiedades_asignadas', models.ManyToManyField(related_name='propietario_asignado_a_propiedad', related_query_name='propietario_asignado_a_la_propiedad', to='appbroker.propiedades')),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.AddField(
            model_name='propiedades',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_asignadas_al_propietario', related_query_name='propiedades_asignadas_a_propietario', to='appbroker.propietarios'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propietarios'),
        ),
        migrations.CreateModel(
            name='Reparymant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('gas', 'Gas'), ('estructura', 'Estructura'), ('varios', 'Varios')], max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('resuelto', 'Resuelto'), ('no_resuelto', 'No resuelto'), ('en_proceso', 'En proceso')], max_length=20)),
                ('costo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.propiedades')),
            ],
            options={
                'verbose_name_plural': 'Reparaciones y mantenimiento',
            },
        ),
    ]
