# Generated by Django 5.0.2 on 2024-02-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
