# Generated by Django 4.2.6 on 2023-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0002_inquilinos_propiedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='baños',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=0),
        ),
    ]
