# Generated by Django 4.2.6 on 2023-12-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0003_alter_propiedades_baños'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparymant',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compradores',
            name='documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compradores',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='valor_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquilinos',
            name='documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquilinos',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inquilinos',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='baños',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='expensas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='valor_alquiler',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='valor_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='reclamante',
            field=models.CharField(blank=True, choices=[('inquilino', 'Inquilino'), ('propietario', 'Propietario'), ('comprador', 'Comprador')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reparymant',
            name='costo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reparymant',
            name='tipo',
            field=models.CharField(blank=True, choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('gas', 'Gas'), ('estructura', 'Estructura'), ('varios', 'Varios')], max_length=20, null=True),
        ),
    ]
