# Generated by Django 5.0.1 on 2024-01-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0004_reparymant_fecha_alter_compradores_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradores',
            options={'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='contratos',
            options={'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='inquilinos',
            options={'verbose_name_plural': 'Inquilinos'},
        ),
        migrations.AlterModelOptions(
            name='propiedades',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='propietarios',
            options={'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='reclamos',
            options={'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AlterModelOptions(
            name='reparymant',
            options={'verbose_name_plural': 'Reparaciones y mantenimiento'},
        ),
        migrations.RemoveField(
            model_name='propietarios',
            name='propiedades',
        ),
        migrations.AddField(
            model_name='propiedades',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_asignadas_al_propietario', related_query_name='propiedades_asignadas_a_propietario', to='appbroker.propietarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietarios',
            name='propiedades_asignadas',
            field=models.ManyToManyField(related_name='propietario_asignado_a_propiedad', related_query_name='propietario_asignado_a_la_propiedad', to='appbroker.propiedades'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbroker.contratos')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
