# Generated by Django 5.0.1 on 2024-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0006_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_inmobiliaria', related_query_name='usuario', to='auth.group', verbose_name='Grupo al que pertenece'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='permisos_usuario_inmobiliaria', related_query_name='usuario', to='auth.permission', verbose_name='Permisos del usuario'),
        ),
    ]
