# Generated by Django 5.0.1 on 2024-01-25 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroker', '0007_user_telefono_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('invitado', 'Invitado'), ('inquilino', 'Inquilino'), ('inmobiliaria', 'Inmobiliaria'), ('propietario', 'Propietario'), ('comprador', 'Comprador')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Nombre de usuario ya existente'}, max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario solo puede contener letras, números y @/./+/-/_.', regex='^[\\w.@+-]+$')]),
        ),
    ]
